kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd
  namespace: default
rules:
  - apiGroups: ['', 'apps', 'batch', 'extensions', 'networking.k8s.io']
    resources:
      [
        'deployments',
        'services',
        'replicasets',
        'pods',
        'jobs',
        'cronjobs',
        'ingresses',
      ]
    verbs: ['*']
