# Fetched from https://raw.githubusercontent.com/crazy-max/docker-matomo/3.13.1-RC6/examples/kubernetes/02-volume.yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: matomo-data-pvc
  namespace: matomo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
